version: "3.8"

services:
  db:
    image: mysql:8
    volumes:
      - mysqldata:/var/lib/postgresql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=classroom-quiz
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysqldata:
